# ---------------- #
#   Main Configs   #
# ---------------- #
#baseurl: https://comsince.github.io
url: https://carlos9310.github.io
date_format: "ordinal"
title: carlos9310
subtitle: "for the learner"
description: "for the learner"
keywords: carlos9310
favicon: /favicon.ico
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: carlos9310
organization: google
organization_url: https://www.google.com
location: HangZhou, China
email: carlos56059310@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基

  -
    href: /open-source/
    label: 开源
    
  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
paginate_path: "/blog/page:num/"
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
plugins:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: carlos9310/carlos9310.github.io

# ---------------- #
#      Socials     #
# ---------------- #
github_username: carlos9310
# douban_username: comsince
# facebook_username: comsince
# weibo_username: comsince
# zhihu_username: comsince
# twitter_username: comsince

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: gittalk
comments_provider: gitalk
# !!!重要!!! 请修改下面两个用户名为你自己申请的
# !!!Important!!! Please modify usernames below to yours

# https://github.com/gitalk/gitalk#install
gitalk:
    owner: carlos9310
    repo: github_pages_comments
    clientID: 32cbf0baaa4c7109354d
    clientSecret: 3c50229777246501ea06517a030097bc96d30b5a

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-92285152-1

# ---------------- #
#      Datas       #
# ---------------- #
skill_software_keywords: [Python,Java, JavaScript, SQL, Design Patterns]
# skill_mobile_app_keywords: [Android, J2EE Engineering]
# skill_windows_keywords: [Java, Android]
